### ISSUE TITLE
@ApiHideProperty() makes property read-only, TypeORM can't assign values to entity

### ISSUE THREAD

**Issue by dsyncerek** [nestjs/swagger#475]
# Bug report

## Current behavior

When you decorate property of TypeORM entity with `@ApiHideProperty()`, you get following error  as the property is read-only - `Cannot assign to read only property 'property' of object '#<Entity>'`.

## Expected behavior

The property shouldn't be read-only, so TypeORM can create class and assign values from db.

## Minimal reproduction of the problem with instructions

Clone: https://github.com/nestjs/nest/tree/master/sample/05-sql-typeorm.

Install @nestjs/swagger (`npm i @nestjs/swagger`).

Decorate property, for example `views` in `photo.entity.ts`.
```typescript
@Column('int')
@ApiHideProperty()
views: number;
```

<details>
<summary>Add a photo to database.</summary>
You can edit `findAll` method in service to ensure that it returns at least one photo (or just add it manually).

```typescript
  async findAll(): Promise<Photo[]> {
    await this.photoRepository.save({
      name: 'test',
      description: 'test',
      filename: 'test',
      views: 99,
      isPublished: true,
    });

    return this.photoRepository.find();
  }
```
</details>

Running the application and navigating to `localhost:3000/photo` causes an error - `Cannot assign to read only property 'views' of object '#<Photo>'`.

## What is the motivation / use case for changing the behavior?

For example, you want to hide some internal properties, like createdAt.

## Environment

<pre>
Nest version: 6.10.14
nestjs/swagger version: 4.1.7
TypeORM driver: pg
</pre>

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/swagger/blob/master/lib/decorators/api-hide-property.decorator.ts
^ see this file. `@ApiHideProperty` is just an empty function.

**Comment by dsyncerek** [comment]
Yes, to be sure I made a following test without TypeORM:

```typescript
import { Controller, Get } from '@nestjs/common';
import { ApiHideProperty } from '@nestjs/swagger';

class Photo {
  id: number;

  @ApiHideProperty()
  name: string;
}

@Controller('photo')
export class PhotoController {
  @Get()
  getPhoto(): Photo {
    const photo = new Photo();

    photo.id = 99; // it works
    photo.name = 'lorem'; // it doesn't: `Cannot assign to read only property 'name' of object '#<Photo>'`

    return photo;
  }
}
```

**Comment by Nosfistis** [comment]
I have also encountered this. It occurs with any property having `ApiHideProperty()`, while trying to insert with TypeORM.

I guess the decorator not returning anything might be messing with TypeORM's decorations, nullifying or setting some of those properties as read-only.

**Comment by cjancsar** [comment]
Got this as well. Just the plugin in general makes fields read-only. Needed to roll back to `4.0.9` in order for things to work.

**Comment by kamilmysliwiec** [comment]
Fixed in 4.1.9. Thanks for reporting

**Comment by dsyncerek** [comment]
@kamilmysliwiec 

After an update to 4.1.9, using `@ApiHideProperty()` gives a compliation error:
`error TS1240: Unable to resolve signature of property decorator when called as an expression.`

**Comment by kamilmysliwiec** [comment]
Oh, sorry! @dsyncerek can you please test with 4.1.10?

**Comment by dsyncerek** [comment]
@kamilmysliwiec works, thanks :)
