### ISSUE TITLE
typeError: methodMetadata.root.map is not a function

### ISSUE THREAD

**Issue by cre8** [nestjs/swagger#1630]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

After upgrading from 8.1.1 to 8.1.2 I get a rejected promise during start:
```
Unhandled Rejection at: Promise {
http_1        |   <rejected> TypeError: methodMetadata.root.map is not a function
http_1        |       at MapIterator.iteratee (/app/node_modules/@nestjs/swagger/dist/swagger-explorer.js:86:40)
http_1        |       at MapIterator.next (/app/node_modules/iterare/lib/map.js:13:39)
http_1        |       at FilterIterator.next (/app/node_modules/iterare/lib/filter.js:12:34)
http_1        |       at IteratorWithOperators.next (/app/node_modules/iterare/lib/iterate.js:21:28)
http_1        |       at Function.from (<anonymous>)
http_1        |       at IteratorWithOperators.toArray (/app/node_modules/iterare/lib/iterate.js:180:22)
http_1        |       at MetadataScanner.scanFromPrototype (/app/node_modules/@nestjs/core/metadata-scanner.js:12:14)
http_1        |       at SwaggerExplorer.generateDenormalizedDocument (/app/node_modules/@nestjs/swagger/dist/swagger-explorer.js:63:56)
http_1        |       at SwaggerExplorer.exploreController (/app/node_modules/@nestjs/swagger/dist/swagger-explorer.js:49:21)
http_1        |       at /app/node_modules/@nestjs/swagger/dist/swagger-scanner.js:48:84
http_1        | } reason: TypeError: methodMetadata.root.map is not a function
```
Downgrading just the package to 8.1.1 removed the error.

### Minimum reproduction code

.

### Expected behavior

Since the update was a patch and not a major change with breaking changes everthing should be allright.

### Package version

8.1.2

### NestJS version

8.1.1

### Node.js version

17

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by buroz** [comment]
@cre8 I added it but nothing changed. already not in that app, but in another app named admins-service that I use express

**Comment by kamilmysliwiec** [comment]
Can you test with 5.1.3?
